version: "3.8"
services:
  mongo:
    image: docker.io/library/mongo:latest
    restart: always
    container_name: duggybuggy-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
